baseURL = 'https://TomD-Sec.github.io'
languageCode = 'en-us'
title = 'Thomas Davey-Spence'
theme = 'tranquilpeak'

[author]
 name = "Thomas Davey-Spence"
 bio = "Software engineer, costume maker & general annoyance."
 job = "Cloud & Software Engineer working in Cyber Security"
 location = "Midlands, United Kingdom"
 gravatarEmail = ""
 picture = "images/20220917_165007.jpg"
 twitter = "tom_DSec"


[params]
  sidebarBehavior = 1
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "images/cover.jpeg"
  favicon = "images/favicon.ico"
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
    [[params.sharingOptions]]
     name = "Facebook"
     icon = "fab fa-facebook-square"
     url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
     name = "Twitter"
     icon = "fab fa-twitter"
     url = "https://twitter.com/intent/tweet?text=%s"
	 
	 
	 
	 [[params.sharingOptions]]
     name = "LinkedIn"
     icon = "fab fa-linkedin"
     url = "https://www.linkedin.com/sharing/share-offsite/?url=%s"

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-bookmark\" aria-hidden=\"true\"></i>"
  url = "/categories"
  [[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/TomD-Sec"
  [[menu.links]]
  weight = 1
  identifier = "LinkedIn"
  name = "LinkedIn"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-linkedin\" aria-hidden=\"true\"></i>"
  url = "https://www.linkedin.com/in/thomas-d-s-sec/"
  [[menu.links]]
  weight = 1
  identifier = "Twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-twitter\" aria-hidden=\"true\"></i>"
  url = "https://twitter.com/tom_d_sec"

[taxonomies]
  tag = "tags"
  category = "categories"